#!/bin/bash
set -e

CONFIG_FILE="/var/www/html/includes/config.php"

# Wait for MySQL to be fully ready (beyond just healthcheck)
echo "Waiting for MySQL to accept connections..."
until mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASS" --ssl-mode=DISABLED -e "SELECT 1" &>/dev/null; do
    sleep 2
done
echo "MySQL is ready."

# Auto-setup if config.php does not exist
if [ ! -f "$CONFIG_FILE" ]; then
    echo "First run detected — setting up TIBST CMS..."

    # Run schema
    mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASS" --ssl-mode=DISABLED "$DB_NAME" < /var/www/html/schema.sql
    echo "Database tables created and seeded."

    # Create admin user via PHP
    php -r "
        \$pdo = new PDO('mysql:host=' . getenv('DB_HOST') . ';dbname=' . getenv('DB_NAME') . ';charset=utf8mb4', getenv('DB_USER'), getenv('DB_PASS'), [PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false]);
        \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        \$hash = password_hash(getenv('ADMIN_PASS'), PASSWORD_DEFAULT);
        \$stmt = \$pdo->prepare('INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, \"admin\")');
        \$stmt->execute([getenv('ADMIN_NAME'), getenv('ADMIN_EMAIL'), \$hash]);
        echo \"Admin user created.\n\";
    "

    # Write config.php
    cat > "$CONFIG_FILE" <<PHPEOF
<?php
/**
 * TIBST CMS Configuration
 * Auto-generated by Docker entrypoint
 */

define('DB_HOST', '${DB_HOST}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
PHPEOF

    chown www-data:www-data "$CONFIG_FILE"
    echo "Config file written."

    # Remove installer for security
    rm -f /var/www/html/install.php
    echo "install.php removed."

    echo "TIBST CMS setup complete!"
else
    echo "Config already exists — skipping setup."
fi

# Hand off to Apache
exec "$@"
